# Docker environment specific configuration
spring:
  data:
    # Docker MongoDB connection
    mongodb:
      uri: mongodb://openframe:password123456789@mongodb-0.mongodb.datasources.svc.cluster.local:27017/openframe?authSource=admin&connectTimeoutMS=10000&socketTimeoutMS=10000&serverSelectionTimeoutMS=10000
    # Docker Cassandra connection
    cassandra:
      contact-points: cassandra.datasources.svc.cluster.local

    # Docker Redis connection (only used by API)
    redis:
      host: redis-headless.datasources.svc.cluster.local
      port: 6379

# Docker logging configuration
logging:
  config: http://openframe-config.microservices.svc.cluster.local:8888/logging/shared-logback-spring.xml

# Docker monitoring endpoints
loki:
  url: http://loki.platform.svc.cluster.local:3100/loki/api/v1/push

# Pinot connection details
pinot:
  controller:
    url: pinot-controller.datasources.svc.cluster.local:9000
  broker:
    url: pinot-broker.datasources.svc.cluster.local:8099

debezium:
  connector:
    create: http://debezium-connect.datasources:8083/connectors
