spring:
  oss-tenant:
    kafka:
      bootstrap-servers: kafka.datasources.svc.cluster.local:9092

oauth:
  client:
    default:
      id: openframe_client
      secret: prod_secret

openframe:
  management:
    url: http://openframe-management.microservices.svc.cluster.local:8095
    key: ${OPENFRAME_MANAGEMENT_KEY:docker-management-key-123}