# Stream service common configuration
server:
  port: 8082

# Management server configuration
management:
  server:
    port: 8083

spring:
  data:
    mongodb:
      enabled: false
    cassandra:
      enabled: true
  autoconfigure:
    exclude:
      - org.apache.pinot.client.PinotClientAutoConfiguration
      - org.apache.pinot.spring.boot.PinotAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  redis:
    enabled: true
  oss-tenant:
    enabled: true
    kafka:
      enabled: true
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          max.request.size: 10485760
          buffer.memory: 10485760
      consumer:
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          "[spring.json.trusted.packages]": "*"
          "[spring.json.use.type.headers]": false
          "[spring.json.value.default.type]": "com.openframe.data.model.debezium.CommonDebeziumMessage"
          # optional if you rely on custom type mapping header:
          "[spring.json.type.mapping]": "debeziumMessage:com.openframe.data.model.debezium.CommonDebeziumMessage"
          max.partition.fetch.bytes: 10485760
          fetch.max.bytes: 10485760
          receive.buffer.bytes: 10485760
  cloud:
    config:
      fail-fast: false
kafka:
  consumer:
    topic:
      event:
        meshcentral:
          name: meshcentral.mongodb.events
        tactical-rmm:
          name: tactical-rmm.postgres.events
        fleet-mdm:
          name: fleet.mysql.events
      stream:
        fleet-mdm:
          activities: fleet.activities.events
          host-activities: fleet.host_activities.events
  producer:
    topic:
      it:
        event:
          name: integrated-tool.events.pinot
# Fleet MDM Configuration
fleet:
  mdm:
    # Base URL for Fleet MDM server
    base-url: http://fleetmdm-server.integrated-tools.svc.cluster.local:8070