# Stream service docker environment configuration
spring:
  oss-tenant:
    kafka:
      bootstrap-servers: kafka.datasources.svc.cluster.local:9092
      consumer:
        group-id: openframe-stream-group

  data:
    redis:
      host: redis-master.datasources.svc.cluster.local
      port: 6379
    mongodb:
      enabled: true
      uri: mongodb://openframe:password123456789@mongodb-0.mongodb.datasources.svc.cluster.local:27017/openframe?authSource=admin&connectTimeoutMS=10000&socketTimeoutMS=10000&serverSelectionTimeoutMS=10000