# Management service docker environment configuration
spring:
  data:
    mongodb:
      uri: mongodb://openframe:password123456789@mongodb-0.mongodb.datasources.svc.cluster.local:27017/openframe?authSource=admin&connectTimeoutMS=10000&socketTimeoutMS=10000&serverSelectionTimeoutMS=10000
    # Docker Redis connection (created from application-k8s.yaml)
    # TODO: Remove this once Redis url is taken from application-k8s.yaml
    redis:
      host: redis-master.datasources.svc.cluster.local
      port: 6379

management:
  key: ${OPENFRAME_MANAGEMENT_KEY:docker-management-key-123}
