# API service docker environment configuration
spring:
  kafka:
    bootstrap-servers: kafka.datasources.svc.cluster.local:9092
  oss-tenant:
    enabled: false
  saas:
    enabled: true
    kafka:
      bootstrap-servers: saas-kafka.datasources.svc.cluster.local:29094
      producer:
        client-id: oss-tenant-saas-producer

oauth:
  client:
    default:
      id: openframe_web_dashboard
      secret: prod_secret

fleet:
  api:
    url: http://fleetmdm-server.integrated-tools.svc.cluster.local:8070

openframe:
  management:
    url: http://openframe-management.microservices.svc.cluster.local:8095
    key: ${OPENFRAME_MANAGEMENT_KEY:docker-management-key-123}
