server:
  port: 8090

# API service common configuration
spring:
  main:
    web-application-type: servlet
  data:
    mongodb:
      enabled: true
    cassandra:
      enabled: true
  redis:
    enabled: true
    timeout: 2000
    connect-timeout: 2000
    lettuce:
      shutdown-timeout: 2000ms
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
    client-type: lettuce
  oss-tenant:
    enabled: true
    kafka:
      producer:
        client-id: oss-tenant-producer
  saas:
    enabled: true
    kafka:
      producer:
        client-id: oss-tenant-saas-producer
  cloud:
    config:
      fail-fast: false
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    path: /graphql

  mail:
    host: localhost
    port: 25

# Management server configuration
management:
  server:
    port: 8091

# GraphQL configuration
dgs:
  graphql:
    path: /graphql
    graphiql:
      enabled: true

openframe:
  security:
    jwt:
      cache:
        expire-after: PT30M
        refresh-after: PT10M
        maximum-size: 1
  invitations:
    ttl-hours: 24
    link-template: "https://localhost/invitations?invitationId={id}"
  mail:
    provider: smtp
  saas:
    kafka:
      topics:
        outbound:
          user-events: user-events

#Available SSO providers to setup
sso:
  providers:
    - displayName: Google SSO
      provider: google