spring:
  data:
    mongodb:
      uri: mongodb://openframe:password123456789@mongodb-0.mongodb.datasources.svc.cluster.local:27017/openframe?authSource=admin&connectTimeoutMS=10000&socketTimeoutMS=10000&serverSelectionTimeoutMS=10000
  redis:
    host: redis-master.datasources.svc.cluster.local
    port: 6379