# Stream service common configuration
server:
  port: 8082

# Management server configuration
management:
  server:
    port: 8083

spring:
  data:
    mongodb:
      enabled: false
    cassandra:
      enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.apache.pinot.client.PinotClientAutoConfiguration
      - org.apache.pinot.spring.boot.PinotAutoConfiguration
  redis:
    enabled: true
  kafka:
    enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: openframe-stream
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  cloud:
    config:
      fail-fast: false
kafka:
  topic:
    event:
      meshcentral:
        name: meshcentral.mongodb.events
      tactical-rmm:
        name: tactical-rmm.postgres.events
  consumer:
    topic:
      event:
        meshcentral:
          name: meshcentral.mongodb.events
        tactical-rmm:
          name: tactical-rmm.postgres.events
  producer:
    topic:
      it:
        event:
          name: integrated-tool.events.pinot