server:
  port: 8090

# API service common configuration
spring:
  main:
    web-application-type: servlet
  data:
    mongodb:
      enabled: true
    cassandra:
      enabled: true
  redis:
    enabled: true
    timeout: 2000
    connect-timeout: 2000
    lettuce:
      shutdown-timeout: 2000ms
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
    client-type: lettuce
  kafka:
    enabled: false
  cloud:
    config:
      fail-fast: false
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    path: /graphql

# Management server configuration
management:
  server:
    port: 8091

# GraphQL configuration
dgs:
  graphql:
    path: /graphql
    graphiql:
      enabled: true

openframe:
  security:
    jwt:
      cache:
        expire-after: PT30M
        refresh-after: PT10M
        maximum-size: 1

#Available SSO providers to setup
sso:
  providers:
    - displayName: Google SSO
      provider: google